---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing kubeadm on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_kubeadm_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "kubeadm is defined"
  tags:
    - "kubeadm"
- name: "Install kubeadm"
  package:
    pkg: "{{ install_kubeadm_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "kubeadm is defined"
  tags:
    - "kubeadm"
